# Generated by Django 3.2.5 on 2021-08-02 03:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_alter_aluno_ano_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_nascimento',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(datetime.datetime(2021, 8, 2, 0, 20, 47, 528393))]),
        ),
    ]
