# Generated by Django 3.2.5 on 2021-08-02 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_alter_aluno_ano_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='ano_nascimento',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(2021)]),
        ),
    ]
